packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@pixpilot/dev-config': ^2.1.0
    '@pixpilot/pnpm-workspace-package-generator': ^1.5.4
    '@pixpilot/semantic-release-require-config': ^1.0.0
    '@rollup/plugin-terser': ^0.4.4
    '@rollup/plugin-typescript': ^12.1.4
    '@semantic-release/changelog': ^6.0.3
    '@semantic-release/commit-analyzer': ^13.0.1
    '@semantic-release/git': ^10.0.1
    '@semantic-release/github': ^11.0.3
    '@semantic-release/npm': ^12.0.2
    '@semantic-release/release-notes-generator': ^14.0.3
    '@turbo/gen': ^2.5.5
    '@types/node': ^22.15.29
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint-config-prettier: ^10.1.8
    husky: ^9.1.7
    lint-staged: ^16.1.2
    prettier: ^3.6.0
    rimraf: ^6.0.1
    rollup: ^4.9.4
    semantic-release: ^24.2.7
    semantic-release-monorepo: ^8.0.2
    tsx: ^4.20.3
    turbo: ^2.5.5
    typescript: ^5.8.3
    vitest: ^3.2.4
  eslint:
    '@eslint-react/eslint-plugin': ^1.52.3
    '@pixpilot/eslint-config': ^2.2.0
    eslint: ^9.28.0
    eslint-plugin-jest: ^29.0.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-turbo: ^2.5.4
    typescript-eslint: ^8.38.0
  prod:
    '@fastify/deepmerge': ^3.1.0
