packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@pixpilot/dev-config': ^2.1.0
    '@pixpilot/pnpm-workspace-package-generator': ^1.5.8
    '@rollup/plugin-terser': ^0.4.4
    '@rollup/plugin-typescript': ^12.1.4
    '@turbo/gen': ^2.5.5
    '@types/node': ^24.2.1
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    eslint-config-prettier: ^10.1.8
    husky: ^9.1.7
    lint-staged: ^16.1.4
    prettier: ^3.6.2
    rimraf: ^6.0.1
    rollup: ^4.46.2
    tsx: ^4.20.3
    turbo: ^2.5.5
    typescript: ^5.9.2
    vitest: ^3.2.4
  eslint:
    '@pixpilot/eslint-config': ^0.0.0
    eslint: ^9.32.0
    eslint-plugin-jest: ^29.0.1
    eslint-plugin-turbo: ^2.5.5
    typescript-eslint: ^8.39.0
  prod:
    '@fastify/deepmerge': ^3.1.0
