packages:
  - 'packages/**'
  - 'tooling/**'

catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@pixpilot/dev-config': ^3.1.0
    '@pixpilot/workspace-package-generator': ^1.0.4
    '@rollup/plugin-terser': ^0.4.4
    '@rollup/plugin-typescript': ^12.1.4
    '@turbo/gen': ^2.5.6
    '@types/node': ^24.3.0
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    husky: ^9.1.7
    lint-staged: ^16.1.5
    prettier: ^3.6.2
    rimraf: ^6.0.1
    rollup: ^4.46.3
    tsx: ^4.20.4
    turbo: ^2.5.6
    typescript: ^5.9.2
    vitest: ^3.2.4
  eslint:
    eslint: ^9.33.0
    eslint-plugin-jest: ^29.0.1
    eslint-plugin-turbo: ^2.5.6
    typescript-eslint: ^8.40.0
  prod:
    '@fastify/deepmerge': ^3.1.0
